server:
  port: 8888
spring:
  application:
    name: gateway-nacos
  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          # 默认为false，设为true开启通过微服务创建路由的功能，即可以通过微服务名访问服务
          # http://localhost:8888/hello-service/sayHello
          enabled: true
      routes:
        - id: nacos-router #值随意，方便记忆并且在所有路由定义中唯一即可
          uri: lb://hello-service #为固定写法，表示开启负载均衡；hello-service即服务在Nacos中注册的名字
          predicates:
            - Path=/hello/** #使用"Path Route Predicate Factory"，规则为/hello开头的任意URI
      # 是否开启网关
      enabled: true