server:
  port: 8001

application:
    name: springcloud-movie

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    format_sql: true
  datasource:
    platform: mysql                  #指定数据源类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud-study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  #    schema: classpath:schema.sql    #指定数据库的建表脚本
  #    data: classpath:data.sql        #指定数据库的数据脚本


logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

