server:
  port: 8000

eureka:
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:9000/eureka/
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: springcloud-ms-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    format_sql: true
  datasource:
    platform: mysql                  #指定数据源类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud-study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  #    schema: classpath:schema.sql    #指定数据库的建表脚本
  #    data: classpath:data.sql        #指定数据库的数据脚本



logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

#Actuator /info
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
    developer: jason
