server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true

#自定义负载均衡规则(从SpringCloud Netflix 1.2.0开始，支持使用属性自定义Ribbon客户端)
springcloud-ms-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

spring:
  application:
    name: springcloud-ms-movie-ribbon
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    format_sql: true
  datasource:
    platform: mysql                  #指定数据源类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud-study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  #    schema: classpath:schema.sql    #指定数据库的建表脚本
  #    data: classpath:data.sql        #指定数据库的数据脚本


logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

