server:
  port: 9000

spring:
  application:
    name: springcloud-eureka

eureka:
  server:
    enable-self-preservation: false #禁用自我保护模式
  client:
    healthcheck:
      enable: true
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/

